#! /bin/sh
source ~/spark-ec2/ec2-variables.sh
export AWS_DEFAULT_REGION=eu-west-1
aws sns publish --topic-arn arn:aws:sns:eu-west-1:378130075212:inreach-prod-slack-alert --message "{\"errorMessage\": \"${CLUSTER_NAME} is being terminated. Please use ${CI_URL} to restart.\"}"
sleep 3 # make sure the message has time to send

exit 0
