./startTrainingOnCluster.sh "--classifier-name NumericVsClassifier_RandomForestClassifier --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name NumericVsClassifier_ProbabilisticMultilayerPerceptronClassifier --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name NumericVsClassifier_ProbabilisticLSHClassifier --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name Word2VecVsClassifier_LogisticRegression --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name TextVsClassifier_LogisticRegression --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name TextVsClassifier_NaiveBayes --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name NumericFundingClassifier_RandomForestClassifier --classifier-wait false"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
./startTrainingOnCluster.sh "--classifier-name ComposingVsClassifier_RandomForestClassifier --classifier-wait true"; (if [ $? != 0 ]; then yes | ./spark-ec2 destroy sparkTraining; fi)
